
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
async pickWorkflowFile() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_workflow_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickSaveFile() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_save_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProject(path: string) : Promise<Result<ProjectData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProject(path: string, workflow: Workflow) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { path, workflow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validate(workflow: Workflow) : Promise<ValidationResult> {
    return await TAURI_INVOKE("validate", { workflow });
},
async nodeTypeDefaults() : Promise<NodeTypeInfo[]> {
    return await TAURI_INVOKE("node_type_defaults");
},
async runWorkflow(request: RunRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_workflow", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWorkflow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_workflow") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuns(query: RunsQuery) : Promise<Result<NodeRun[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadRunEvents(query: RunEventsQuery) : Promise<Result<TraceEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_run_events", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readArtifactBase64(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_artifact_base64", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAsset(projectPath: string) : Promise<Result<ImportedAsset | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_asset", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiStepParams = { prompt: string; button_text: string | null; template_image: string | null; max_tool_calls: number | null; allowed_tools: string[] | null }
export type AppDebugKitParams = { operation_name: string; parameters: JsonValue }
export type Artifact = { artifact_id: string; kind: ArtifactKind; path: string; metadata: JsonValue; overlays: JsonValue[] }
export type ArtifactKind = "Screenshot" | "Ocr" | "TemplateMatch" | "Log" | "Other"
export type Check = { name: string; check_type: CheckType; params: JsonValue; on_fail: OnCheckFail }
export type CheckType = "TextPresent" | "TextAbsent" | "TemplateFound" | "WindowTitleMatches"
export type ClickParams = { target: string | null; button: MouseButton; click_count: number }
export type Edge = { from: string; to: string }
export type EndpointConfig = { base_url: string; model: string; api_key: string | null }
export type FindImageParams = { template_image: string | null; threshold: number; max_results: number }
export type FindTextParams = { search_text: string; match_mode: MatchMode; scope: string | null; select_result: string | null }
export type FocusMethod = "WindowId" | "AppName" | "TitlePattern"
export type FocusWindowParams = { method: FocusMethod; value: string | null; bring_to_front: boolean }
export type ImportedAsset = { relative_path: string; absolute_path: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ListWindowsParams = { app_name: string | null; title_pattern: string | null }
export type MatchMode = "Contains" | "Exact"
export type MouseButton = "Left" | "Right" | "Center"
export type Node = { id: string; node_type: NodeType; position: Position; name: string; enabled: boolean; timeout_ms: number | null; retries: number; trace_level: TraceLevel; expected_outcome: string | null; checks: Check[] }
export type NodeRun = { run_id: string; node_id: string; started_at: number; ended_at: number | null; status: RunStatus; trace_level: TraceLevel; events: TraceEvent[]; artifacts: Artifact[]; observed_summary: string | null }
export type NodeType = ({ type: "AiStep" } & AiStepParams) | ({ type: "TakeScreenshot" } & TakeScreenshotParams) | ({ type: "FindText" } & FindTextParams) | ({ type: "FindImage" } & FindImageParams) | ({ type: "Click" } & ClickParams) | ({ type: "TypeText" } & TypeTextParams) | ({ type: "Scroll" } & ScrollParams) | ({ type: "ListWindows" } & ListWindowsParams) | ({ type: "FocusWindow" } & FocusWindowParams) | ({ type: "AppDebugKitOp" } & AppDebugKitParams)
export type NodeTypeInfo = { name: string; category: string; icon: string; node_type: NodeType }
export type OnCheckFail = "FailNode" | "WarnOnly"
export type Position = { x: number; y: number }
export type ProjectData = { path: string; workflow: Workflow }
export type RunEventsQuery = { project_path: string; workflow_id: string; node_id: string; run_id: string }
export type RunRequest = { workflow: Workflow; project_path: string | null; agent: EndpointConfig; transform: EndpointConfig; vlm: EndpointConfig | null; mcp_command: string }
export type RunStatus = "Ok" | "Failed" | "Stopped"
export type RunsQuery = { project_path: string; workflow_id: string; node_id: string }
export type ScreenshotMode = "Screen" | "Window" | "Region"
export type ScrollParams = { delta_y: number; x: number | null; y: number | null }
export type TakeScreenshotParams = { mode: ScreenshotMode; target: string | null; include_ocr: boolean }
export type TraceEvent = { timestamp: number; event_type: string; payload: JsonValue }
export type TraceLevel = "Off" | "Minimal" | "Full"
export type TypeTextParams = { text: string; press_enter: boolean }
export type ValidationResult = { valid: boolean; errors: string[] }
export type Workflow = { id: string; name: string; nodes: Node[]; edges: Edge[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
